# Generated by Django 5.2.5 on 2025-08-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='primary_completion_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
